.\" This file is part of QtMC.
.\" Copyright 2012, Hans van Leeuwen
.\"
.\" QMC is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU Lesser General Public License as published
.\" by the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.TH QtMC 1 "May 25, 2012"
.SH NAME
qtmc \- QtMC
.SH SYNOPSIS
.B qtmc
.RI [ OPTIONS ]...
.RI [ filename|URI ]...
.SH DESCRIPTION
Put your bla bla here
.SH OPTIONS
.TP
.B \-\-help|-?
Outputs help.
.TP
.B \-\-version
Outputs version information and exits.
.SH BUGS
Bugs? Impossible! ;-)
.PP
.SH AUTHOR
This manual page was written by Hans van Leeuwen <hansvl@gmail.com>
